package view;

import java.awt.*;
import javax.swing.*;

/**
 * Ventana principal de la aplicación de gestión cinematográfica
 * 
 * Responsabilidades:
 * - Proporcionar el contenedor principal de la interfaz gráfica
 * - Organizar los componentes visuales (toolbar, formulario)
 * - Gestionar el layout de la aplicación
 * - Proporcionar acceso a los componentes para el controlador
 * 
 * Características:
 * - Diseño BorderLayout para organización flexible
 * - Toolbar con acciones principales
 * - Integración con PeliculaFormPanel
 * - Tamaño y posición centrada por defecto
 * 
 */
public class MainFrame extends javax.swing.JFrame {
    
    // Componentes de la interfaz
    private final JToolBar toolbar = new JToolBar();
    private final JButton btnAgregar = new JButton("Agregar");
    private final JButton btnModificar= new JButton("Modificar");
    private final JButton btnEliminar = new JButton("Eliminar");
    private final JButton btnListar   = new JButton("Listar");

    private final PeliculaFormPanel formPanel = new PeliculaFormPanel();
    private final ModificarPeliculaPanel modificarPanel = new ModificarPeliculaPanel();
    private final EliminarPeliculaPanel eliminarPanel = new EliminarPeliculaPanel();
    private final ListarPeliculasPanel listarPanel = new ListarPeliculasPanel();
    
    private final JPanel cardPanel = new JPanel(new CardLayout());


    /**
     * Constructor de la ventana principal
     * 
     * Inicializa:
     * - Título y propiedades de la ventana
     * - Layout y organización de componentes
     * - Toolbar con botones de acción
     * - Formulario de películas
     * 
     */
    public MainFrame() {
        initComponents();
        
        // Limpiar el contenido generado por NetBeans
        getContentPane().removeAll();
        
        setTitle("Gestión Cine Magenta");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 500);
        setLocationRelativeTo(null);
        
        // Configurar el layout después de limpiar
        getContentPane().setLayout(new BorderLayout());
        
        // Configurar panel de cards
        cardPanel.add(formPanel, "AGREGAR");
        cardPanel.add(modificarPanel, "MODIFICAR");
        cardPanel.add(eliminarPanel, "ELIMINAR");
        cardPanel.add(listarPanel, "LISTAR");

        // Toolbar
        toolbar.add(btnAgregar);
        toolbar.add(btnModificar);   btnModificar.setEnabled(true); btnModificar.setToolTipText("Permite modificar una película existente");
        toolbar.add(btnEliminar);    btnEliminar.setEnabled(true);  btnEliminar.setToolTipText("Permite eliminar una película existente");
        toolbar.add(btnListar);      btnListar.setEnabled(true);    btnListar.setToolTipText("Permite listar todas las películas y filtrarlas por género y rango de fechas");
        
        getContentPane().add(toolbar, BorderLayout.NORTH);
        getContentPane().add(cardPanel, BorderLayout.CENTER);

        // Forzar actualización del layout
        revalidate();
        repaint();
    }
    
    public JButton getBtnAgregar()     { return btnAgregar; }
    public JButton getBtnModificar() { return btnModificar; }
    public JButton getBtnEliminar() { return btnEliminar; }
    public JButton getBtnListar() { return btnListar; }
    
    public PeliculaFormPanel getFormPanel(){ return formPanel; }
    public ListarPeliculasPanel getListarPanel() { return listarPanel; }
    public ModificarPeliculaPanel getModificarPanel() { return modificarPanel; }
    public EliminarPeliculaPanel getEliminarPanel() { return eliminarPanel; }
    
    public void mostrarPanel(String nombre) {
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, nombre);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
